#ifndef ZBYRATORTYPESV2DEFS_H
#define ZBYRATORTYPESV2DEFS_H

#define MPH_INITSTATE       0
#define MPH_REQUEST_QUEUE   1
#define MPH_ADDED_2_QUEUE   2
#define MPH_LEAVED_QUEUE    3


#endif // ZBYRATORTYPESV2DEFS_H
